### ISSUE TITLE
Generated PDB files have incompatible HEADER line

### ISSUE THREAD

**Issue by tzok** [mmagnus/rna-pdb-tools#48]
The effort to have normalized PDB files of RNAPuzzles models is amazing, thanks for that! I have just a small comment and feature request. In generated PDB files you are using `HEADER` lines to provide some comments. But `HEADER` is actually [a well-structured entry](http://www.wwpdb.org/documentation/file-format-content/format33/sect2.html#HEADER). This behaviour breaks current PDB parsers which make use of the `HEADER` line. Additionally, `HEADER` is allowed to be present only once in a file.

In my opinion it would be better to facilitate some PDB field that has a free-text form. For example, [KEYWDS](http://www.wwpdb.org/documentation/file-format-content/format33/sect2.html#KEYWDS) seems to be a good fit:

> The KEYWDS record contains a set of terms relevant to the entry. Terms in the KEYWDS record provide a simple means of categorizing entries and may be used to generate index files. __This record addresses some of the limitations found in the classification field of the HEADER record__. It provides the opportunity to add further annotation to the entry in a concise and computer-searchable fashion.

**Comment by mmagnus** [comment]
@tzok thanks Tomek. OK, I will look into it and change it asap. :-)

**Comment by mmagnus** [comment]
@tzok  and there is always `--no_hr               do not insert the header into files` argument, so you will not get any headers ;)
