### ISSUE TITLE
PDB files are getting truncated

### ISSUE THREAD

**Issue by filipsPL** [mmagnus/rna-pdb-tools#61]
For many PDB files, after using rna_pdb_tools (in both: command line and as python module) I get the truncated pdb file. Like:

`./rna_pdb_toolsx.py --get_rnapuzzle_ready rna.pdb  > out.pdb`

(for input and output see [pdbs.zip](https://github.com/mmagnus/rna-pdb-tools/files/1527778/pdbs.zip))

The input file is generated by chimera (mol2 file) and then converted to pdb by openbabel. Both pymol and chimera open and interpret the input pdb files correctly.

**Comment by filipsPL** [comment]
Some insights into the "wrong input" pdb files:

The file fragment giving wrong/truncated results:
```
ATOM      1  O5' G1  A   1       0.909  27.528  -2.558  1.00  0.00
ATOM      2  C5' G1  A   1       1.375  26.201  -2.300  1.00  0.00
ATOM      3  C4' G1  A   1       1.389  25.895  -0.820  1.00  0.00
ATOM      4  O4' G1  A   1       0.064  26.134  -0.274  1.00  0.00
```

For comparison, the file giving good results:
```
ATOM      1  C5'  G1 A   1       1.375  26.201  -2.300  1.00  0.00
ATOM      2  O5'  G1 A   1       0.909  27.528  -2.558  1.00  0.00
ATOM      3  C4'  G1 A   1       1.389  25.895  -0.820  1.00  0.00
ATOM      4  O4'  G1 A   1       0.064  26.134  -0.274  1.00  0.00
```

The difference is *the position of the residue name*, however in both cases it conforms the PDB file specification:

Column 18 - 20: Residue name

(according to http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM)

**Comment by mmagnus** [comment]
Yeah, I see now. The residue name should not have numbers. Cleaning could be implemented in RPT or in a separate script. If this is an "isolated" case I would write a script to clean it before RPT.
